[package]
name = "abstract-cw-multi-test"
version = "3.0.0-rc"
authors = [
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
    "Dariusz Depta <depta@engos.de>",
]
description = "Testing tools for multi-contract interactions"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"
license = "Apache-2.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["staking", "stargate", "cosmwasm_3_0"]
staking = ["cosmwasm-std/staking"]
stargate = ["cosmwasm-std/stargate"]
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1"]
cosmwasm_1_2 = ["cosmwasm_1_1", "cosmwasm-std/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm_1_2", "cosmwasm-std/cosmwasm_1_3"]
cosmwasm_1_4 = ["cosmwasm_1_3", "cosmwasm-std/cosmwasm_1_4"]
cosmwasm_2_0 = ["cosmwasm_1_4", "cosmwasm-std/cosmwasm_2_0"]
cosmwasm_2_1 = ["cosmwasm_2_0", "cosmwasm-std/cosmwasm_2_1"]
cosmwasm_2_2 = ["cosmwasm_2_1", "cosmwasm-std/cosmwasm_2_2"]
cosmwasm_3_0 = ["cosmwasm_2_2", "cosmwasm-std/cosmwasm_3_0"]

[dependencies]
bech32 = "0.11.0"
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "zk-mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }
cw20-ics20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "zk-mvp" }
itertools = "0.14.0"
prost = "0.14.1"
schemars = "0.8"
serde = "1.0.219"
sha2 = "0.10.9"
thiserror = "1.0.64"

serde_json = "1.0.140"
log = "0.4.20"
hex = "0.4.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
once_cell = "1.20.2"
cw-multi-test = { package = "abstract-cw-multi-test", git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "zk-mvp" }
